global:
  scrape_interval: 60s     # Scrape metrics every 5 seconds for responsive CDC dashboards
  evaluation_interval: 5s

scrape_configs:
  - job_name: "zebridge"
    metrics_path: "/metrics"
    static_configs:
      # Scrapes ZeBridge whether running in Docker container ('bridge:27434') or on host ('host.docker.internal:27434')
      - targets: ["127.0.0.1:27434", "127.0.0.1:27435",]
        labels:
          environment: "production"
          service: "cdc-bridge"

  - job_name: "nats"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["127.0.0.1:7777"]
        labels:
          environment: "production"
          service: "nats-server"

remote_write:
  - url: https://prometheus-prod-55-prod-gb-south-1.grafana.net/api/prom/push
    basic_auth:
      username: "2500869"
      password: glc_eyJvIjoiMTQ1NzY0NyIsIm4iOiJzdGFjay0xMjg4MzE3LWFsbG95LXplcmJpZGdlIiwiayI6IllqOTFSZTc2bTZGMzFuMFZub0dmNjdiVSIsIm0iOnsiciI6InByb2QtZ2Itc291dGgtMSJ9fQ==