#!/usr/bin/env bash
# A regional nats-server as a LEAF of the dev hub (NOTES §10hl), in a container on OrbStack.
#
#   examples/08-map/leaf/leaf.sh          # build nats-leaf.conf from the hub's conf, start the container
#   examples/08-map/leaf/leaf.sh stop
#
# The leaf runs in operator mode with the SAME operator and account JWTs as the hub (copied
# from scripts/native/nats-server-jwt.conf, so a phone's creds are verified at the edge),
# no JetStream, and one remote: the hub's leaf port, entered with the account credential
# `leaf-nantes.creds` (minted under the SERVICE key — the link carries every principal's
# traffic, so its grant is the union; narrowing it is a later question).
# Phones connect to the Mac's 4223, monitoring is 8223.
#
# What crosses the link: core subjects — `query.<tenant>.<name>` and the replies. What
# does NOT: the JetStream API (`$JS.API.>` from a leaf finds no responder on a standalone
# hub; the ways around it are recorded in NOTES §10hl). So a phone on the leaf asks
# locally, and the responder on the leaf feeds its replica from the hub directly:
#   poi_service.py --url nats://hub:4222 --serve-url nats://127.0.0.1:4223 --label leaf
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"
HUB="$ROOT/scripts/native/nats-server-jwt.conf"
CREDS="$ROOT/scripts/native/creds"
case "${1:-start}" in
  stop) docker --context orbstack rm -f nats-leaf >/dev/null 2>&1 && echo "leaf stopped"; exit 0;;
esac
python3 - "$HUB" "$HERE/nats-leaf.conf" <<'PY'
import re, sys
hub = open(sys.argv[1]).read()
op = re.search(r'^operator: (ey\S+)', hub, re.M).group(1)
sysacc = re.search(r'^system_account: (\S+)', hub, re.M).group(1)
preload = re.search(r'^resolver_preload: \{.*?^\}', hub, re.M | re.S).group(0)
zeb = re.search(r'// Account "ZEBRIDGE"\s*\n\s*([A-Z2-7]{56}):', hub).group(1)
open(sys.argv[2], 'w').write(f'''# Generated by leaf.sh from the hub's conf — a regional leaf, operator mode, no JetStream.
operator: {op}
system_account: {sysacc}
resolver: MEMORY
{preload}

port: 4222
http_port: 8222

leafnodes {{
  remotes = [
    {{ url: "nats-leaf://host.docker.internal:7422", account: "{zeb}", credentials: "/creds/leaf-nantes.creds" }}
  ]
}}
''')
print(f"nats-leaf.conf written: ZEBRIDGE {zeb[:8]}… binds to the hub's leaf port")
PY
docker --context orbstack rm -f nats-leaf >/dev/null 2>&1 || true
docker --context orbstack run -d --name nats-leaf -p 4223:4222 -p 8223:8222 \
  -v "$HERE/nats-leaf.conf":/etc/nats/nats-leaf.conf:ro -v "$CREDS/leaf-nantes.creds":/creds/leaf-nantes.creds:ro \
  nats:latest -c /etc/nats/nats-leaf.conf >/dev/null
echo "leaf container started: phones on nats://127.0.0.1:4223, monitoring http://127.0.0.1:8223"
