#!/usr/bin/env python3
"""`nats.zig` speaks TLS — the capability that makes bridge/NATS colocation a choice.

The v1.0 topology colocates the bridge and `nats-server` on one VPS because the Zig
client historically had no TLS ("no link to encrypt" was the mitigation, not the goal).
Upstream `nats.zig` now ships TLS (server-authenticated and mutual, via tls.zig), which
reopens remote topologies: a bridge publishing to a distant NATS — e.g. a per-tenant
leaf holding cadence-built snapshots (NOTES.md §1.12, "Delta generations") — over a
link that is actually encrypted.

⚠️ The library's own e2e suite already proves core pub/sub over TLS
(`TEST_FILTER="tls e2e" zig build test-e2e` inside `nats.zig/`, needs Docker). What it
does NOT cover is JetStream — the bridge's actual workload — so this scenario builds a
small Zig probe against the vendored submodule and runs the bridge's shapes over
`tls://`: stream create, acked publish, durable pull consumer, fetch, ack.

Two assertions, and the negative one matters as much as the positive:

  1. CA-verified `tls://` connect (the submodule's test CA) + the JetStream round trip;
  2. the same connect WITHOUT the CA must fail with a certificate error — proving the
     handshake actually verifies, rather than silently not encrypting or skipping
     verification.

Standalone on purpose: no `zb` import, no NATS_URL, no running stack — it starts its
own `nats-server` (host binary, TLS-only listener + JetStream) on a scratch port and
tears it down. Python here is orchestration only; the system under test is Zig.

Usage:  python scripts/scenarios/tls.py
Needs:  nats-server and zig on PATH. Skips (exit 0) if nats-server is absent.
"""

import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import time

ROOT = pathlib.Path(__file__).resolve().parents[2]
CERTS = ROOT / "nats.zig" / "tests" / "configs" / "certs"
PORT = 14245  # scratch — outside 4222 (stack) and 142xx (nats.zig's own e2e range ends at 14232)

PROBE_MAIN = '''
// JetStream over TLS, the bridge's workload shape. Generated by scripts/scenarios/tls.py.
const std = @import("std");
const nats = @import("nats");

pub fn main(init: std.process.Init) !void {
    // Zig 0.16 "Juicy Main": argv arrives via std.process.Init, same as src/args.zig.
    var args = init.minimal.args.iterate();
    _ = args.next(); // argv[0]
    const mode = args.next() orelse "verified";
    const url = args.next() orelse return error.MissingUrl;
    const ca = args.next();

    var conn = nats.Connection.init(init.gpa, init.io, .{
        .tls = if (ca) |path| .{ .ca_file = path } else .{},
    });
    defer conn.deinit();

    if (std.mem.eql(u8, mode, "no-ca")) {
        // Must FAIL: the test CA is not in the system trust store, so a verifying
        // client cannot accept this server. Success here would mean verification
        // is not happening.
        const r = conn.connect(url);
        if (r) |_| return error.UnverifiedConnectAccepted else |err| switch (err) {
            error.CertificateIssuerNotFound => {
                std.log.info("REFUSED-WITHOUT-CA: {}", .{err});
                return;
            },
            else => return err,
        }
    }

    try conn.connect(url);
    var js = conn.jetstream(.{});

    var si = try js.addStream(.{
        .name = "TLS_PROBE",
        .subjects = &[_][]const u8{"tlsprobe.>"},
        .storage = .file,
    });
    defer si.deinit();

    var ack = try js.publish("tlsprobe.one", "jetstream over tls", .{});
    defer ack.deinit();

    var sub = try js.pullSubscribe("tlsprobe.>", "tls_probe_worker", .{ .stream = "TLS_PROBE" });
    defer sub.deinit();

    var batch = try sub.fetch(1, .{ .duration = .{ .raw = .fromSeconds(5), .clock = .awake } });
    defer batch.deinit();
    if (batch.messages.len != 1) return error.NoMessage;
    const msg = batch.messages[0];
    if (!std.mem.eql(u8, msg.msg.data, "jetstream over tls")) return error.WrongPayload;
    try msg.ack();

    std.log.info("TLS-JETSTREAM-OK seq={d}", .{ack.value.seq});
}
'''

PROBE_BUILD = '''
const std = @import("std");
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const nats_dep = b.dependency("nats", .{ .target = target, .optimize = optimize });
    const exe = b.addExecutable(.{
        .name = "probe",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    exe.root_module.addImport("nats", nats_dep.module("nats"));
    b.installArtifact(exe);
}
'''

# The fingerprint is per-package-name; zig prints the expected value on mismatch, and
# `0x0` is never it — see the bootstrap in main() that reads it back from the error.
PROBE_ZON = '''
.{
    .name = .zb_tls_probe,
    .version = "0.0.1",
    .fingerprint = %s,
    .minimum_zig_version = "0.16.0",
    .dependencies = .{ .nats = .{ .path = "nats.zig" } },
    .paths = .{""},
}
'''


def ok(msg): print(f"  \033[32m✓\033[0m {msg}")
def bad(msg): print(f"  \033[31m✗\033[0m {msg}")


def main() -> int:
    if shutil.which("nats-server") is None:
        print("  ⓘ  nats-server not on PATH — skipping (this scenario provisions its own server)")
        return 0
    for f in ("ca.pem", "server-cert.pem", "server-key.pem"):
        if not (CERTS / f).exists():
            bad(f"missing {CERTS / f} — is the nats.zig submodule checked out?")
            return 1

    failed = 0
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="zb_tls_"))
    server = None
    try:
        # ── the server: TLS-only listener, JetStream on ──────────────────────
        (tmp / "js").mkdir()
        conf = tmp / "server.conf"
        conf.write_text(
            f'listen: 127.0.0.1:{PORT}\n'
            f'jetstream {{ store_dir: "{tmp}/js" }}\n'
            f'tls {{\n  cert_file: "{CERTS}/server-cert.pem"\n  key_file: "{CERTS}/server-key.pem"\n}}\n'
        )
        server_log = (tmp / "server.log").open("w")
        server = subprocess.Popen(["nats-server", "-c", str(conf)], stdout=server_log, stderr=server_log)
        for _ in range(50):
            if "Server is ready" in (tmp / "server.log").read_text():
                break
            time.sleep(0.1)
        else:
            bad("nats-server did not become ready")
            return 1

        # ── the probe: a scratch Zig package against the submodule ───────────
        probe = tmp / "probe"
        (probe / "src").mkdir(parents=True)
        (probe / "src" / "main.zig").write_text(PROBE_MAIN)
        (probe / "build.zig").write_text(PROBE_BUILD)
        (probe / "nats.zig").symlink_to(ROOT / "nats.zig")
        (probe / "build.zig.zon").write_text(PROBE_ZON % "0x0")
        r = subprocess.run(["zig", "build"], cwd=probe, capture_output=True, text=True)
        if r.returncode != 0 and "use this value:" in r.stderr:
            fp = r.stderr.split("use this value:")[1].split()[0].rstrip(";")
            (probe / "build.zig.zon").write_text(PROBE_ZON % fp)
            r = subprocess.run(["zig", "build"], cwd=probe, capture_output=True, text=True)
        if r.returncode != 0:
            bad(f"probe build failed:\n{r.stderr[-2000:]}")
            return 1
        exe = probe / "zig-out" / "bin" / "probe"
        url = f"tls://localhost:{PORT}"

        # ── 1. CA-verified JetStream round trip ──────────────────────────────
        r = subprocess.run([exe, "verified", url, str(CERTS / "ca.pem")],
                           capture_output=True, text=True, timeout=30)
        if r.returncode == 0 and "TLS-JETSTREAM-OK" in r.stderr + r.stdout:
            ok("JetStream over CA-verified tls://: stream create, acked publish, pull fetch, ack")
        else:
            bad(f"verified probe failed (exit {r.returncode}):\n{(r.stderr + r.stdout)[-1500:]}")
            failed += 1

        # ── 2. verification is real: no CA → refused ─────────────────────────
        r = subprocess.run([exe, "no-ca", url], capture_output=True, text=True, timeout=30)
        if r.returncode == 0 and "REFUSED-WITHOUT-CA" in r.stderr + r.stdout:
            ok("and without the CA the handshake is refused (CertificateIssuerNotFound) — verification is real")
        else:
            bad(f"no-ca probe did not refuse (exit {r.returncode}):\n{(r.stderr + r.stdout)[-1500:]}")
            failed += 1
    finally:
        if server:
            server.terminate()
            server.wait(timeout=5)
        shutil.rmtree(tmp, ignore_errors=True)

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
