#!/usr/bin/env python3
"""What TLS costs on the bridge's hop to NATS — measured, not assumed (NOTES §10fy).

    python scripts/scenarios/tls_cost.py            (manual; minutes, not part of any battery)

The bridge publishes to JetStream synchronously, one acknowledged publish per group of
events. This probe does the same with the same library (nats.zig, the vendored
submodule), against two nats-server instances that differ only in TLS: one plain, one
TLS-only with the submodule's test certificates. Three message sizes: one small event,
a medium batch, a large batch. For each: messages per second, megabytes per second,
the probe's CPU time and the server's CPU time, median of three runs, plain then TLS.
Everything runs on localhost, the bridge's real topology.

Needs nats-server and zig on PATH. Starts and removes its own servers and files.
"""
import pathlib, shutil, statistics, subprocess, sys, tempfile, time

ROOT = pathlib.Path(__file__).resolve().parents[2]
CERTS = ROOT / "nats.zig" / "tests" / "configs" / "certs"
PLAIN_PORT, TLS_PORT = 14246, 14247
SIZES = [(400, 60_000), (16_000, 12_000), (256_000, 1_500)]  # (bytes per message, messages)
RUNS = 3

PROBE_MAIN = r'''
// JetStream publish throughput, plain or TLS. Generated by scripts/scenarios/tls_cost.py.
const std = @import("std");
const nats = @import("nats");

pub fn main(init: std.process.Init) !void {
    var args = init.minimal.args.iterate();
    _ = args.next();
    const mode = args.next() orelse return error.MissingMode; // plain | tls
    const url = args.next() orelse return error.MissingUrl;
    const ca = args.next() orelse return error.MissingCa;
    const size = try std.fmt.parseInt(usize, args.next() orelse return error.MissingSize, 10);
    const count = try std.fmt.parseInt(usize, args.next() orelse return error.MissingCount, 10);
    const tls = std.mem.eql(u8, mode, "tls");

    var conn = nats.Connection.init(init.gpa, init.io, .{
        .tls = if (tls) .{ .ca_file = ca } else null,
    });
    defer conn.deinit();
    try conn.connect(url);
    var js = conn.jetstream(.{});

    var si = try js.addStream(.{
        .name = "TLS_COST",
        .subjects = &[_][]const u8{"tlscost.>"},
        .storage = .file,
    });
    defer si.deinit();

    const payload = try init.gpa.alloc(u8, size);
    defer init.gpa.free(payload);
    for (payload, 0..) |*b, i| b.* = @truncate(i *% 2654435761);

    var i: usize = 0;
    while (i < count) : (i += 1) {
        var ack = try js.publish("tlscost.x", payload, .{});
        ack.deinit();
    }
    std.log.info("PUBLISHED {d}", .{count});
}
'''

PROBE_BUILD = r'''
const std = @import("std");
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const nats_dep = b.dependency("nats", .{ .target = target, .optimize = optimize });
    const exe = b.addExecutable(.{
        .name = "probe",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    exe.root_module.addImport("nats", nats_dep.module("nats"));
    b.installArtifact(exe);
}
'''

PROBE_ZON = '''
.{
    .name = .zb_tls_cost,
    .version = "0.0.1",
    .fingerprint = %s,
    .minimum_zig_version = "0.16.0",
    .dependencies = .{ .nats = .{ .path = "nats.zig" } },
    .paths = .{""},
}
'''


def cpu_seconds(pid: int) -> float:
    """Cumulative CPU time of a process (user + system), from `ps -o time`."""
    t = subprocess.run(["ps", "-o", "time=", "-p", str(pid)], capture_output=True, text=True).stdout.strip()
    if not t:
        return 0.0
    parts = t.replace("-", ":").split(":")
    secs = 0.0
    for p in parts:
        secs = secs * 60 + float(p)
    return secs


def start_server(tmp: pathlib.Path, name: str, port: int, tls: bool) -> subprocess.Popen:
    (tmp / name).mkdir()
    conf = tmp / f"{name}.conf"
    text = f'listen: 127.0.0.1:{port}\nmax_payload: 1048576\njetstream {{ store_dir: "{tmp}/{name}" }}\n'
    if tls:
        text += f'tls {{\n  cert_file: "{CERTS}/server-cert.pem"\n  key_file: "{CERTS}/server-key.pem"\n}}\n'
    conf.write_text(text)
    log = tmp / f"{name}.log"
    proc = subprocess.Popen(["nats-server", "-c", str(conf)], stdout=log.open("w"), stderr=subprocess.STDOUT)
    for _ in range(100):
        if "Server is ready" in log.read_text():
            return proc
        time.sleep(0.1)
    raise RuntimeError(f"{name} server did not become ready")


def build_probe(tmp: pathlib.Path) -> pathlib.Path:
    probe = tmp / "probe"
    (probe / "src").mkdir(parents=True)
    (probe / "src" / "main.zig").write_text(PROBE_MAIN)
    (probe / "build.zig").write_text(PROBE_BUILD)
    (probe / "nats.zig").symlink_to(ROOT / "nats.zig")
    (probe / "build.zig.zon").write_text(PROBE_ZON % "0x0")
    cmd = ["zig", "build", "-Doptimize=ReleaseFast"]
    r = subprocess.run(cmd, cwd=probe, capture_output=True, text=True)
    if r.returncode != 0 and "use this value:" in r.stderr:
        fp = r.stderr.split("use this value:")[1].split()[0].rstrip(";")
        (probe / "build.zig.zon").write_text(PROBE_ZON % fp)
        r = subprocess.run(cmd, cwd=probe, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"probe build failed:\n{r.stderr[-2000:]}")
    return probe / "zig-out" / "bin" / "probe"


def run_once(exe, mode, port, server, size, count):
    url = f"{'tls' if mode == 'tls' else 'nats'}://localhost:{port}"
    s0 = cpu_seconds(server.pid)
    t0 = time.perf_counter()
    r = subprocess.run(["/usr/bin/time", "-p", str(exe), mode, url, str(CERTS / "ca.pem"), str(size), str(count)],
                       capture_output=True, text=True, timeout=600)
    wall = time.perf_counter() - t0
    s1 = cpu_seconds(server.pid)
    if r.returncode != 0 or "PUBLISHED" not in r.stderr:
        raise RuntimeError(f"probe failed ({mode}, {size} B):\n{r.stderr[-1500:]}")
    user = float(next(l.split()[1] for l in r.stderr.splitlines() if l.startswith("user ")))
    sys_ = float(next(l.split()[1] for l in r.stderr.splitlines() if l.startswith("sys ")))
    return {"wall": wall, "client_cpu": user + sys_, "server_cpu": s1 - s0}


def main() -> int:
    if shutil.which("nats-server") is None or shutil.which("zig") is None:
        print("  ⓘ  nats-server or zig not on PATH — skipping")
        return 0
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="zb_tls_cost_"))
    servers = []
    try:
        exe = build_probe(tmp)
        plain = start_server(tmp, "plain", PLAIN_PORT, tls=False); servers.append(plain)
        secure = start_server(tmp, "tls", TLS_PORT, tls=True); servers.append(secure)
        print(f"{'size':>9} {'msgs':>7} | {'mode':5} {'msgs/s':>9} {'MB/s':>8} {'client CPU':>11} {'server CPU':>11}")
        results = {}
        for size, count in SIZES:
            for mode, port, server in (("plain", PLAIN_PORT, plain), ("tls", TLS_PORT, secure)):
                runs = [run_once(exe, mode, port, server, size, count) for _ in range(RUNS)]
                wall = statistics.median(r["wall"] for r in runs)
                ccpu = statistics.median(r["client_cpu"] for r in runs)
                scpu = statistics.median(r["server_cpu"] for r in runs)
                results[(size, mode)] = (wall, ccpu, scpu)
                print(f"{size:>8}B {count:>7} | {mode:5} {count / wall:>9.0f} {count * size / wall / 1e6:>8.1f} {ccpu:>10.2f}s {scpu:>10.2f}s")
            pw, pc, ps_ = results[(size, "plain")]
            tw, tc, ts = results[(size, "tls")]
            print(f"{'':>17} | TLS/plain: time x{tw / pw:.2f}, client CPU x{tc / max(pc, 0.01):.2f}, server CPU x{ts / max(ps_, 0.01):.2f}")
        return 0
    finally:
        for s in servers:
            s.terminate()
            try: s.wait(timeout=5)
            except Exception: s.kill()
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
