/* zb.h: libzb's C ABI. Generated by scripts/gen-header.py from src/capi.zig.
 * Do not edit: change the code, then run the script.
 *
 * Every string goes in and out as UTF-8 JSON (or a plain C string where noted).
 * Strings you pass are read during the call and never kept.
 * A `char *` result is yours: free it with zb_free(). A `const char *` result belongs
 * to the library: do not free it.
 * A call that fails returns {"error": "<Name>"} (plus "detail"), except
 * zb_client_connect, which returns 0 and leaves the reason in zb_last_error().
 * One thread owns a handle; only zb_client_wake may be called from another.
 */
#ifndef ZB_H
#define ZB_H

#include <stdint.h>

#define ZB_ABI_VERSION 6

#ifdef __cplusplus
extern "C" {
#endif

/* The version of this C ABI. A host checks it against the version its own declarations were written for. */
int zb_abi_version(void);

/* Frees a string this library returned. Every `char *` result goes back through here, once. */
void zb_free(char *p);

/* Runs a pure rule of the library's core, with no client: `fn_name` names it ("mergeRegisters"), `args_json` carries its arguments. Returns JSON. Free the result with zb_free(). */
char *zb_call(const char *fn_name, const char *args_json);

/* Opens the local replica and the NATS connection. `opts_json` holds the options (dbPath, tables, natsUrl and creds, or bridgeUrl and invite). Returns a handle, or 0 on failure: the reason is in zb_last_error(). */
uint64_t zb_client_connect(const char *opts_json);

/* Why the last zb_client_connect on this thread returned 0. NULL once a connect succeeds. The library owns the string: do not free it. */
const char *zb_last_error(void);

/* Closes the connection and the replica. Returns 0, or 1 for an unknown handle. */
int zb_client_close(uint64_t handle);

/* Closes the client and deletes its replica files. Returns 0, or 1 for an unknown handle. */
int zb_client_wipe(uint64_t handle);

/* The SHA-256 (hex) of the wire grammar this library was built with, to compare with the bridge's. Free the result with zb_free(). */
char *zb_grammar_hash(void);

/* The wire grammar this library was built with, as JSON. Free the result with zb_free(). */
char *zb_grammar_json(void);

/* Builds the text of a `.creds` file from the JWT that /enroll returned and the seed from zb_create_user. Free the result with zb_free(). */
char *zb_creds_file_text(const char *jwt, const char *seed);

/* Ends a zb_client_poll that is waiting, at once. The only call allowed from a thread that does not own the handle. Returns 0, or 1 for an unknown handle. */
int zb_client_wake(uint64_t handle);

/* A register stamp on the bridge's clock, for cooperative editing (the `t` beside a value). Free the result with zb_free(). */
char *zb_client_stamp(uint64_t handle);

/* 1 if the principal was revoked, 0 if not, -1 for an unknown handle. */
int zb_client_revoked(uint64_t handle);

/* How many client handles are open in this process. For leak checks in tests. */
int zb_client_live(void);

/* Generates the key pair a device enrolls with: {"publicKey", "seed"}. The seed is the private half: keep it on the device. Free the result with zb_free(). */
char *zb_create_user(void);

/* Follows one more tenant: its stream, and its rows in the same local tables. Returns {"tenants": [...]}. Free the result with zb_free(). */
char *zb_client_join(uint64_t handle, const char *tenant);

/* Stops following a tenant: its rows leave the local tables. Returns {"tenants": [...]}. Free the result with zb_free(). */
char *zb_client_leave(uint64_t handle, const char *tenant);

/* The first call after connect: resolves the tenant, applies the schemas, seeds the tables, catches up on the streams. Returns {"principal", "tenant", "tenants", "first", "unseeded"}. Free the result with zb_free(). */
char *zb_client_sync(uint64_t handle);

/* Reads the local replica. `params_json` is a JSON array of the `?` parameters. Returns {"columns", "rows"}. Free the result with zb_free(). */
char *zb_client_query(uint64_t handle, const char *sql, const char *params_json);

/* One write: applied locally at once, then sent. `op` is INSERT, UPDATE or DELETE; `key_json` and `values_json` are JSON objects. Returns {"msgId"}: the poll report's outcomes name it. Free the result with zb_free(). */
char *zb_client_mutate(uint64_t handle, const char *table, const char *op, const char *key_json, const char *values_json);

/* zb_client_mutate with the caller's own version stamp (RFC 3339, UTC). Free the result with zb_free(). */
char *zb_client_mutate_at(uint64_t handle, const char *table, const char *op, const char *key_json, const char *values_json, const char *version);

/* Answers questions on this client's connection. `opts_json`: {"tenants", "queries"}. The questions arrive in the poll report's `requests`. Free the result with zb_free(). */
char *zb_client_serve(uint64_t handle, const char *opts_json);

/* Answers one question from the poll report's `requests`. Returns {"replied"}. Free the result with zb_free(). */
char *zb_client_reply(uint64_t handle, uint64_t id, const char *answer_json);

/* Waits up to `wait_ms` for changes, applies them and collects verdicts. Blocks the calling thread. Returns {"applied", "settled", "changed_tables", "seeded", "outcomes", "pending"}. Free the result with zb_free(). */
char *zb_client_poll(uint64_t handle, uint64_t wait_ms);

/* Asks a service (`subject` is query.<tenant>.<name>) and waits up to `timeout_ms` for its answer. Free the result with zb_free(). */
char *zb_client_request(uint64_t handle, const char *subject, const char *payload_json, uint64_t timeout_ms);

/* Writes a service's answer ({"columns", "rows"}) into a local on-demand table. `scope_json` is optional. Free the result with zb_free(). */
char *zb_client_ingest(uint64_t handle, const char *table, const char *answer_json, const char *scope_json);

/* Sends the queued writes and waits up to `wait_ms` for their verdicts. Returns {"sent", "settled", "verdicts"}. Free the result with zb_free(). */
char *zb_client_flush_outbox(uint64_t handle, uint64_t wait_ms);

#ifdef __cplusplus
}
#endif

#endif /* ZB_H */
